Feature/34
collaborative-2023-g3/pj-group3 pull request #35
Opened 2024-01-13 14:46 UTC by kzog14

# issue(対応しているissueを貼る！)
[【猫募集】猫登録_バックエンド#34](https://github.com/collaborative-2023-g3/pj-group3/issues/34)
# 概要
下記記事の、CORSの設定の前に相当するところまで実装。
https://qiita.com/kazama1209/items/1a0186f635f14a8161d8#%E4%B8%8D%E8%A6%81%E3%81%AA%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E6%95%B4%E7%90%86
# 変えたこと・実装内容

# 確認したこと
- ローカル環境での確認 : (○)
  - 何を確認した？
    - 下記コマンドでcatsテーブルにデータが登録されること。
    -  /public/uploads/cat/image配下に画像が格納されること。
  curl -F "name=ねこ太郎" -F "breed=三毛猫" -F "date_of_birth=2023/1/1" -F "sex=1" -F "uid=test@example.com" -F "image=@/Users/kzog14/sample.jpeg" http://localhost:3000/v1/cats

    -  下記コマンドでcatsテーブルから猫データが取得できること。
curl -X GET http://localhost:3000/v1/cats
- 開発環境での確認 : (×)
- ユニットテストの実装 : (×)

# 変えたドキュメント(あれば)
スプレッドシートのERDを修正しました。
https://docs.google.com/spreadsheets/d/1Qavelva38QyGFl-3XhiZfrxMIoPjNZEDw0jYjMzqyIo/edit#gid=1961249319

2024-01-14 01:02 UTC, junichi-fukushima requested changes

2024-01-14 01:02 UTC, junichi-fukushima commented on test/models/cat_test.rb
テストは作成しないので、削除してください。(今存在している他のテストファイルも全て削除ください)

2024-01-14 01:02 UTC, junichi-fukushima commented on app/helpers/v1/cats_helper.rb
使わないファイルは削除よろです

2024-01-14 01:02 UTC, junichi-fukushima commented on test/controllers/v1/cats_controller_test.rb
テストは作成しないので、削除してください。(今存在している他のテストファイルも全て削除ください)
testディレクトリ配下全ていらないかも

2024-01-14 01:02 UTC, junichi-fukushima commented on test/fixtures/cats.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
このファイル入ります？

2024-01-14 01:53 UTC, kzog14 commented on app/controllers/v1/cats_controller.rb
> +      cat[:status] = 1
rubyの定数の記法を確認して、CAN_APPLY_STATUS = 1　と定義しました。

2024-01-14 01:53 UTC, kzog14 commented on test/models/cat_test.rb
削除しました。

2024-01-14 01:54 UTC, kzog14 commented on app/helpers/v1/cats_helper.rb
削除しました。

2024-01-14 01:54 UTC, kzog14 commented on test/controllers/v1/cats_controller_test.rb
削除しました。

2024-01-14 01:54 UTC, kzog14 commented on test/fixtures/cats.yml
> +# Read about fixtures at https://api.rubyonrails.org/classes/ActiveRecord/FixtureSet.html
削除しました。

2024-01-16 11:31 UTC, junichi-fukushima approved these changes

2024-01-19 10:21 UTC, sayzkkgw approved these changes
お疲れ様でした。

2024-01-23 02:59 UTC, merged