Feature/39 frontend (猫登録フロント）
collaborative-2023-g3/pj-group3 pull request #47
Opened 2024-01-24 14:51 UTC by sayzkkgw

# issue(対応しているissueを貼る！)
【猫募集】猫登録_フロントエンド #39

*バックエンド　#35 

# 概要
- 猫登録のフロントページの実装

# 変えたこと・実装内容
- フロントエンド実装（基本的にAuthRegisterの転用
- 画像送信するのでformDataを使用してAPI送信
- AuthRegisterで、アカウント登録時にlocalStorageにUIDを追加
- 猫登録時にlocalStorageからUIDを取得してパラメーターにセットしてリクエスト送信

# 確認したこと
- ローカル環境での確認 : (○)
  - 何を確認した？　＝＞フロントページでアカウント・猫登録して、catテーブルにレコードが追加されること

<img width="1069" alt="Screenshot 2024-01-24 at 23 50 25" src="https://github.com/collaborative-2023-g3/pj-group3/assets/56593880/6289473f-de0f-4020-87ae-3138fb426190">
<img width="1144" alt="Screenshot 2024-01-24 at 23 50 45" src="https://github.com/collaborative-2023-g3/pj-group3/assets/56593880/cc77e98f-f47a-47ca-96f9-bc8ee9a040c2">

- 開発環境での確認 : (○)
- ユニットテストの実装 : (×)

# 変えたドキュメント(あれば)

2024-01-25 01:20 UTC, junichi-fukushima requested changes

2024-01-25 01:20 UTC, junichi-fukushima commented on app/assets/stylesheets/pages/CatsCreate/_style.scss
> +.p-signup {
- app/assets/stylesheets/pages/AuthRegister/_style.scss
と記載が被っています。DRYの原則は意識してほしいですー。

- そもそも、CatsCreateなので
p-cats-createというクラス名にするべきでは？？

<修正方針>
CSSがかぶっているので、
app/assets/stylesheets/templates/Form/_style.scssに集約したいです。

2024-01-25 01:20 UTC, junichi-fukushima commented on app/assets/stylesheets/templates/Form/_style.scss
> +@use "../../utility/colors" as *;
シングルクオテーションにしてください

2024-01-25 01:20 UTC, junichi-fukushima commented on app/javascript/pages/CatsCreate/index.tsx
> +            const response = await fetch('http://localhost:3000/api/v1/cat', {
app/javascript/utility/urls.js
で定義してくださいー

2024-01-25 01:20 UTC, junichi-fukushima commented on app/javascript/templates/Header/index.tsx
> +    localStorage.removeItem('uid');
ありがとうございます！！

2024-01-25 01:20 UTC, junichi-fukushima commented on app/javascript/application.js
> +      <Route exact path="/cats/create" element={<CatsCreate />} />
cats/newの方が良い気がします。

2024-01-25 01:20 UTC, junichi-fukushima commented on app/javascript/templates/Header/index.tsx
>              <li><Link to="/my">マイページ</Link></li>
/myではなく、cats/newへ一旦パス変えてもらえると助かります！

2024-01-25 01:21 UTC, junichi-fukushima commented
DBに登録できている感じgoodです！！
登録成功したらトップページに戻る感じにしたいお気持ちです。

![スクリーンショット 2024-01-25 10 20 31](https://github.com/collaborative-2023-g3/pj-group3/assets/71912259/c874cfd1-ec16-4db0-8e6c-c02073efc199)

2024-01-25 01:28 UTC, junichi-fukushima commented on app/javascript/pages/CatsCreate/index.tsx
app/javascript/pages/Cat/New/index.tsx
にしますかねー

2024-01-25 01:31 UTC, junichi-fukushima commented on app/assets/stylesheets/pages/_pages.scss
> +@use "../pages/CatsCreate/style" as CatsCreate;
ここも
@use "../pages/Cat/New/style" as CatsNew;
的な感じにしましょうか

2024-01-26 01:13 UTC, sayzkkgw commented on app/assets/stylesheets/pages/CatsCreate/_style.scss
> +// .p-signup {
Fixしました

2024-01-26 01:16 UTC, sayzkkgw commented on app/assets/stylesheets/templates/Form/_style.scss
> +@use "../../utility/colors" as *;
Fixしました

2024-01-26 01:21 UTC, sayzkkgw commented on app/javascript/pages/CatsCreate/index.tsx
> +            const response = await fetch('http://localhost:3000/api/v1/cat', {
catUrlで一旦定義しました

2024-01-26 01:25 UTC, sayzkkgw commented on app/javascript/pages/CatsCreate/index.tsx
Fixしました

2024-01-26 01:30 UTC, sayzkkgw commented on app/assets/stylesheets/pages/_pages.scss
> +@use "../pages/CatsCreate/style" as CatsCreate;
Fixしました

2024-01-26 01:40 UTC, sayzkkgw commented on app/javascript/templates/Header/index.tsx
>              <li><Link to="/my">マイページ</Link></li>
Fixしました

2024-01-26 01:40 UTC, sayzkkgw commented on app/javascript/application.js
> +      <Route exact path="/cats/create" element={<CatsCreate />} />
Fixしました

2024-01-26 01:57 UTC, sayzkkgw commented on app/assets/stylesheets/_reset.scss
> -label[for] {
Fixしました

2024-01-26 02:48 UTC, sayzkkgw commented on app/assets/stylesheets/pages/CatsCreate/_style.scss
> +.p-signup {
集約のリファクタリング方法がわからず時間かかりそうなので、一旦クラス名のみ変更いたしました。

2024-01-26 02:51 UTC, sayzkkgw commented
<img width="829" alt="Screenshot 2024-01-26 at 11 51 07" src="https://github.com/collaborative-2023-g3/pj-group3/assets/56593880/b966f370-bf0e-4d80-82e7-dbdf5cbb0b25">
小川さんにしていただいたFix後、猫登録に成功したら200コードが返ってくることを確認しました。

2024-01-26 09:47 UTC, merged